"""
PDF Report Generator for V2T Game Analysis.
Produces a professional, structured PDF report from AnalysisOutput.
"""

from __future__ import annotations

import io
import os
from datetime import datetime
from typing import Any

from app.models import AnalysisOutput


def generate_pdf_report(output: AnalysisOutput, filename: str = "game_analysis") -> bytes:
    """
    Generate a professional PDF report from AnalysisOutput.
    Returns PDF bytes.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            HRFlowable,
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        raise ImportError("reportlab not installed. Run: pip install reportlab")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    W, _ = A4

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#555555"),
        spaceAfter=20,
    )
    h1_style = ParagraphStyle(
        "H1",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=colors.HexColor("#16213e"),
        spaceBefore=16,
        spaceAfter=6,
        borderPad=4,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=styles["Heading2"],
        fontSize=11,
        textColor=colors.HexColor("#0f3460"),
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=9,
        leading=14,
        textColor=colors.HexColor("#333333"),
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=body_style,
        leftIndent=12,
        bulletIndent=4,
        spaceBefore=2,
    )
    code_style = ParagraphStyle(
        "Code",
        parent=styles["Code"],
        fontSize=8,
        leading=12,
        textColor=colors.HexColor("#2d2d2d"),
        backColor=colors.HexColor("#f5f5f5"),
    )

    def hr():
        return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0e0e0"), spaceAfter=8)

    def section_header(text: str):
        return [
            Paragraph(text, h1_style),
            hr(),
        ]

    def bullet_list(items: list[str]):
        if not items:
            return [Paragraph("— No data detected", bullet_style)]
        return [Paragraph(f"• {item}", bullet_style) for item in items]

    def kv_table(data: list[tuple[str, str]]):
        table_data = [[k, v] for k, v in data]
        t = Table(table_data, colWidths=[60 * mm, 110 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1a1a2e")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        return t

    def confidence_bar_text(score: int) -> str:
        filled = int(score / 5)
        empty = 20 - filled
        bar = "█" * filled + "░" * empty
        return f"{bar}  {score}/100"

    # -----------------------------------------------------------------------
    # Build story
    # -----------------------------------------------------------------------
    story = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Cover
    story.append(Spacer(1, 20 * mm))
    story.append(Paragraph("🎮 Game Analysis Report", title_style))
    story.append(Paragraph(f"Generated by V2T Analyzer — {now}", subtitle_style))
    story.append(Spacer(1, 5 * mm))

    # Confidence
    story.append(Paragraph("Analysis Confidence", h2_style))
    story.append(Paragraph(confidence_bar_text(output.confidence_score), code_style))
    story.append(Spacer(1, 4 * mm))

    # Technical summary
    story.append(Paragraph("Summary", h2_style))
    story.append(Paragraph(output.technical_summary, body_style))

    if output.assumptions:
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Assumptions & Flags", h2_style))
        story.extend(bullet_list(output.assumptions))

    story.append(PageBreak())

    # --- Section 1: UI/UX ---
    story.extend(section_header("1. UI / UX Analysis"))
    ui = output.ui_ux
    story.append(kv_table([
        ("Layout Type", ui.layout_model.get("type", "—")),
        ("Theme", ui.design_tokens.get("theme", "—")),
        ("Primary Color", ui.design_tokens.get("primary_color", "—")),
        ("UI Consistency", ui.design_tokens.get("ui_consistency", "—")),
    ]))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("HUD Elements", h2_style))
    story.extend(bullet_list(ui.hud_elements))

    story.append(Paragraph("UI Components", h2_style))
    story.extend(bullet_list(ui.component_map))

    if ui.accessibility_issues:
        story.append(Paragraph("Accessibility Issues", h2_style))
        story.extend(bullet_list(ui.accessibility_issues))

    story.append(PageBreak())

    # --- Section 2: Gameplay ---
    story.extend(section_header("2. Gameplay Analysis"))
    gp = output.gameplay
    story.append(kv_table([
        ("Genre", gp.genre),
        ("Target Audience", getattr(gp, "target_audience", "—")),
        ("Difficulty", gp.difficulty_curve),
        ("Progression", gp.progression_system or "—"),
    ]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Core Loop", h2_style))
    story.append(Paragraph(gp.core_loop or "—", body_style))
    story.append(Paragraph("Mechanics Detected", h2_style))
    story.extend(bullet_list(gp.mechanics))
    story.append(Paragraph("Player Actions", h2_style))
    story.extend(bullet_list(gp.player_actions))

    story.append(PageBreak())

    # --- Section 3: Visual Design ---
    story.extend(section_header("3. Visual Design"))
    vd = output.visual_design
    story.append(kv_table([
        ("Art Style", vd.art_style),
        ("Lighting", getattr(vd, "lighting_style", "—")),
        ("UI Consistency", vd.ui_consistency),
        ("Overall Polish", getattr(vd, "overall_polish", "—")),
    ]))
    story.append(Spacer(1, 4 * mm))

    if vd.color_palette:
        story.append(Paragraph("Color Palette", h2_style))
        story.extend(bullet_list(vd.color_palette))

    story.append(Paragraph("VFX Notes", h2_style))
    story.extend(bullet_list(vd.vfx_notes))

    story.append(PageBreak())

    # --- Section 4: Code Architecture ---
    story.extend(section_header("4. Technical Architecture"))
    ca = output.code_architecture
    story.append(kv_table([
        ("Recommended Stack", ca.recommended_stack or "—"),
        ("Patterns Detected", ", ".join(ca.detected_patterns) or "—"),
    ]))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("Suggested Folder Structure", h2_style))
    story.append(Paragraph(
        ca.folder_tree.replace("\n", "<br/>").replace(" ", "&nbsp;"),
        code_style,
    ))

    dm = ca.data_models
    if dm.get("tables"):
        story.append(Paragraph("Inferred Database Tables", h2_style))
        for tbl in dm["tables"]:
            name = tbl.get("name", "?")
            fields = ", ".join(tbl.get("fields", []))
            story.append(Paragraph(f"<b>{name}</b>({fields})", bullet_style))

    if dm.get("sql"):
        story.append(Paragraph("Generated SQL", h2_style))
        story.append(Paragraph(
            dm["sql"].replace("\n", "<br/>"),
            code_style,
        ))

    api = ca.api_contract
    if api.get("endpoints"):
        story.append(Paragraph("Inferred API Endpoints", h2_style))
        for ep in api["endpoints"]:
            story.append(Paragraph(
                f"<b>{ep.get('method','GET')}</b> {ep.get('path','')}  — {ep.get('purpose','')}",
                bullet_style,
            ))

    story.append(PageBreak())

    # --- Section 5: Performance ---
    story.extend(section_header("5. Performance & Scalability"))
    perf = output.performance
    story.append(kv_table([
        ("Scalability Class", perf.scalability_class),
        ("Est. Monthly Cost", str(perf.estimated_monthly_cost)),
    ]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Optimization Notes", h2_style))
    story.extend(bullet_list(perf.optimization_notes))
    story.append(Paragraph("Identified Bottlenecks", h2_style))
    story.extend(bullet_list(perf.bottlenecks))

    story.append(PageBreak())

    # --- Section 6: Monetization ---
    story.extend(section_header("6. Monetization & Market Fit"))
    mono = output.monetization
    story.append(kv_table([
        ("Monetization Model", mono.detected_model),
        ("Revenue Potential", mono.revenue_potential),
    ]))
    story.append(Spacer(1, 4 * mm))

    if mono.iap_elements:
        story.append(Paragraph("IAP Elements Detected", h2_style))
        story.extend(bullet_list(mono.iap_elements))

    story.append(Paragraph("Market Fit Notes", h2_style))
    story.extend(bullet_list(mono.market_fit_notes))

    # --- Footer note ---
    story.append(Spacer(1, 10 * mm))
    story.append(hr())
    story.append(Paragraph(
        f"V2T Analyzer — Confidential Report — {now}",
        ParagraphStyle("Footer", parent=body_style, fontSize=7, textColor=colors.grey),
    ))

    doc.build(story)
    return buf.getvalue()


def save_report(output: AnalysisOutput, output_dir: str = "reports") -> str:
    """Save PDF to disk and return file path."""
    os.makedirs(output_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(output_dir, f"game_analysis_{ts}.pdf")
    pdf_bytes = generate_pdf_report(output)
    with open(path, "wb") as f:
        f.write(pdf_bytes)
    return path
